Fix Copyright Headers
efabless/sky130_klayout_pdk pull request #11
Opened 2023-08-25 15:29 UTC by donn

* Fixes license to match that in the root of the repo
* Assign copyright to misspelled/and/or non-existent legal entities to Efabless Corporation as per our contractual agreement
cc @mkkassem

2023-08-25 15:38 UTC, atorkmabrains requested changes
@donn @mkkassem Please make the changes requested.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/vpp.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/vias.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/via_generator.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/rf.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_poly_klayout_panel.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_poly_child.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_metal_klayout_panel.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_metal_child.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_klayout_panel.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_diff_klayout_panel.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/res_diff_child.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/parent_res.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/layers_def.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/gr.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/globals.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/fet.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/draw_vpp.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/draw_rf.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/draw_guard_ring.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/draw_fet.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/draw_diode.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/draw_bjt.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/diode.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/cap.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/bjt.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-25 15:38 UTC, atorkmabrains commented on sky130_tech/tech/sky130/pymacros/cells/__init__.py
@donn and @mkkassem That was not developed by Efabless and it was not funded by Efabless. This part of the PDK, we agreed to move it while keeping all attributions to Mabrains. Please don't remove Mabrains headers or Skywater 130nm pdk development from the header.

2023-08-26 14:51 UTC, donn commented
Your attitude precludes my further involvement in this matter. You could have fixed these notices. Instead, you have elected to write 27 comments out of spite and wasted my time further.

2023-08-28 12:21 UTC, atorkmabrains commented
@donn and @mkkassem I have completed the updates that we have agreed on. Thanks @donn for all the help.

2023-08-28 12:22 UTC, merged